### PR TITLE
Response status code for the POST, DELETE and PUT

### PR DESCRIPTION
**Pull request by sudipto1989**
All the response will return 200 as the codes are executed on local machine and since no element is created post the POST call so the ideal outcome will be just checking whether the call was made to that particular method or not so the status code for all the methods: GET, POST, PUT, DELETE will be 200.
This holds true only for the endpoint test file created in realtime they can relate with appropriate status code viz. GET, PUT,DELETE: 200; POST: 201 for successful result.

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
The original status codes make the test cases failed. Changes are good.

**Comment by vinc456** [comment]
I noticed this issue as well and believe sudipto1989's pull request is acceptable.

**Comment by rtorres90** [comment]
The changes are very good. We need this code merged to evade more confusions for the students.

**Comment by erezak** [comment]
The POST should return 201. DELETE may return 204. All of the rest should return 200

**Pull request closed without merging**
